### PR TITLE
Fix security issues with tokml

### PR DESCRIPTION
**Pull request by semaja2**
Swapped to @maphubs version of tokml

Prettier ran on commit causing some code to reformat

### CODE REVIEW

**Comment by haoliangyu** [comment]
@semaja2 I know @mapbox/tokml is kind of abundant. Do you know the maintainability of the @maphubs version?

**Comment by semaja2** [comment]
I had submitted a security pull request on the @maphubs version hoping it would be accepted, but nothing so far

Unfortunately the @mapbox has not been touched in 5 years and appears to be abandoned :(

Seems the other option would be to fork tokml again to maintain it, or find another module to replace it, but I couldn't see many others if any out there

**Comment by haoliangyu** [comment]
For the security concern, I would rather maintain my own fork and enable to security update in the repo. I should be able to submit the update soon.

**Comment by haoliangyu** [comment]
I have made the update at v1.4.2. Thanks for the PR.

**Pull request closed without merging**
